config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: 'homes#index'

  resources 'rides' do
    collection do
      get 'search'
      get 'verify'
    end
  end

  resources 'connections', :only => %w[index create] do
    collection do
      get 'accept'
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :address_1, :city, :state, presence: true
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :user
  belongs_to :ride

  validates :user_id, :ride_id, presence: true
  validates_uniqueness_of :ride_id, :scope => :user_id,
                          :message => "You already connected with this ride. If there is no response yet please search again and find another ride."

  after_create :send_emails

  def status
    self.accept? ? "Contact #{ride.user.full_name} at #{ride.business_email}" : "Pending Approval by driver"
  end

  def send_emails
    UserMailer.send_connection_request(self.id).deliver
    UserMailer.send_connection_request_receipt(self.ride_id, user_id).deliver
  end
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  has_many :connections, :dependent => :destroy

  validates :origin, :destination, :total_seat, :user, :business_email, :business_name, :commute_days,
            :origin_address, :destination_address, :leave_at, :return_at, presence: true
  validates_format_of :business_email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z0-9.-]+\z/

  scope :search_by_origin_destination, lambda { |origin, destination| where("origin = ? AND destination = ?", origin, destination).order("destination") }
  scope :search_by_destination, lambda { |destination| where("destination = ?", destination).order("destination") }

  def status
    self.class.to_s.gsub("Ride", "")
  end
end

app/models/ride_offer.rb
class RideOffer < Ride
end

app/models/ride_request.rb
class RideRequest < Ride
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rides, :dependent => :destroy
  has_many :connections, :dependent => :destroy

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_uniqueness_of :email, :message => "Email in use. Try a new email or sign in."
  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z0-9.-]+\z/
  validates_presence_of :password, :unless => :encrypted_password
  validates_confirmation_of :password

  before_validation :force_email_lowercase
  before_validation :strip_email_whitespace

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def strip_email_whitespace
    if self.email
      email_no_whitespace = self.email.strip
      self.email = email_no_whitespace
    end
  end

  def force_email_lowercase
    if self.email
      email_downcase = self.email.downcase
      self.email = email_downcase
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @connections = current_user.connections
  end

  def create
    @connection = Connection.new(connection_params)
    @connection.user_id = current_user.id
    if @connection.save
        redirect_to connections_path, :notice => "Successfully added connection request."
    else
      redirect_to root_path, :notice => "#{@connection.errors.first}"
    end
  end

  def accept
    find_models
    @connection.accept = true
    @connection.save
    redirect_to root_path, :notice => "Thank you for accepting carpool request!"
  end

  private

  def find_models
    @connection = Connection.where(:id => params[:id]).take
  end

  def connection_params
    params.require(:connection).permit(:ride_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # before_action :authenticate_user!

  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :authenticate_user!

  def index
    @rides = current_user.rides.order("type")
  end

  def search
    find_params
    @rides = []
    if @origin.present? && @destination.present?
      @rides = Ride.search_by_origin_destination(@origin, @destination)
    elsif @destination.present?
      @rides = Ride.search_by_destination(@destination)
    end
  end

  def new
    @ride = Ride.new
  end

  def create
    @ride = new_ride
    @ride.user_id = current_user.id
    @ride.commute_days = commute_days
    if @ride.save
      UserMailer.verify_work_email(@ride.id).deliver
      redirect_to rides_path, :notice => "Successfully added ride. Please check your work email and verify it."
    else
      flash.now[:alert] = "#{@ride.errors.first}"
      render :action => :new
    end
  end

  def edit
    find_models
  end

  def update
    find_models
    @ride.commute_days = commute_days
    if @ride.update_attributes(ride_params)
      redirect_to rides_url
    else
      flash.now[:alert] = "#{@ride.errors.first.to_s}"
      render :action => "edit"
    end
  end

  def destroy
    find_models
    @ride.destroy
    redirect_to rides_url
  end

  def verify
    find_models
    @ride.verified_business_email = true
    @ride.save
    redirect_to rides_path, :notice => "Thank you for verifying your work email!"
  end

  private

  def find_models
    @ride = Ride.where(:id => params[:id], :user_id => current_user.id).take
  end

  def find_params
    @origin = params[:ride][:origin]
    @destination = params[:ride][:destination]
  end

  def ride_params
    params.require(:ride).permit(:type, :origin, :destination, :total_seat, :business_name,
                                 :business_email, :origin_address, :destination_address, :leave_at, :return_at)
  end

  def new_ride
    ride_type = params[:ride][:type]
    if ride_type == "RideOffer"
      @ride = RideOffer.new(ride_params)
    else
      @ride = RideRequest.new(ride_params)
    end
  end

  def commute_days
    if params[:commute_days].present?
      params[:commute_days].join(" ")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rides_helper.rb
module RidesHelper
  def leave_home_at
    timings = ['5:00', '5:30', '6:00', '6:30', '7:00', '7:30', '8:00', '8:30', '9:00', '9:30', '10:00', '10:30', '11:00']
    timings.collect { |p| [ "#{p} am", "#{p} am" ] }
  end

  def leave_work_at
    timings = ['3:00', '3:30', '4:00', '4:30', '5:00', '5:30', '6:00', '6:30', '7:00', '7:30', '8:00', '8:30', '9:00', '9:30', '10:00', '10:30']
    timings.collect { |p| [ "#{p} pm", "#{p} pm" ] }
  end
end

app/views/connections/index.html.erb
<div id="available_rides" class="center">
  <h1>My Connection/Requests</h1>

  <div id="rides">
    <table class="table table-striped table-condensed">
      <thead>
      <tr>
        <td class="bold">Origin</td>
        <td class="bold">Destination</td>
        <td class="bold">Company or Business</td>
        <td class="bold">Days</td>
        <td class="bold">Time</td>
        <td class="bold">Accepted?</td>
        <td class="bold">Actions</td>
      </tr>
      </thead>
      <tbody>
      <% @connections.each do |connection| %>
          <% ride = connection.ride %>
          <tr id="ride_<%= ride.id %>">
            <td>
              <%= ride.origin %> <br>
              <%= ride.origin_address %>
            </td>
            <td>
              <%= ride.destination %> <br>
            </td>
            <td>
              <%= ride.business_name %>&nbsp;(<%= ride.business_email %>) <br>
              <%= ride.destination_address %>
            </td>
            <td>
              <%= ride.commute_days %>
            </td>
            <td>
              Leave : <%= ride.leave_at %> <br>
              Return: <%= ride.return_at %>
            </td>
            <td>
              <%= connection.status %>
            </td>
            <td>
              <%= link_to "Delete", "", :method => :delete, data: {confirm: "Are you sure you won't to cancel your request to carpool?"},
                          :class => "btn btn-small btn-danger" %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/homes/index.html.erb
<div id="search_carpool" class="center">
  <h1>Find a carpool</h1>
</div>

<div class="row center">
  <%= form_for :ride, url: search_rides_url, method: :get do |form| %>
      <%= form.text_field :origin, placeholder: "Origin", class: "search-query" %>
      <%= form.text_field :destination, placeholder: "Destination", class: "search-query" %>
      <%= form.submit "Search", class: "btn btn-large btn-success" %>
  <% end %>
</div>

<div class="center">
  <h1>OR</h1>
</div>

<div class="row center mt30">
  <%= link_to "Request or Offer a Ride", new_ride_path, :id => "create_new_ride", :class => "btn btn-large btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carpool</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "CommuteUp", root_path, class: "navbar-brand" %>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <% if current_user %>
            <li><%= link_to "My Rides", rides_path %></li>
            <li><%= link_to "My Connection Requests", connections_path %></li>
      <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><%= link_to "#{current_user.full_name}", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <% if notice %>
        <div class="notice"><%= notice %></div>
    <% end %>
    <% if alert %>
        <div class="alert"><%= alert %></div>
    <% end %>
    <div class="span12"><%= yield %></div>
  </div>
</div>
</body>
</html>

app/views/rides/_form.html.erb
<div>
  <%= form.radio_button("type", "RideRequest") %> Request &nbsp;
  <%= form.radio_button("type", "RideOffer") %> Offer
</div>

<div class="mt20">
  <%= form.text_field :origin, placeholder: "Origin City" %>
</div>

<div class="mt20">
  <%= form.text_field :origin_address, placeholder: "Origin Address", :class => "input-large" %>
</div>

<div class="mt20">
  <%= form.text_field :destination, placeholder: "Destination" %>
</div>

<div class="mt20">
  <%= form.text_field :destination_address, placeholder: "Destination Address", :class => "input-large" %>
</div>

<div class="mt20">
  <%= form.text_field :business_name, placeholder: "Company or Business Name" %>
</div>

<div class="mt20">
  <%= form.text_field :business_email, placeholder: "Work Email" %>
</div>

<div class="mt20">
  Commute days: <br>

  <% ["M", "T", "W", "Th", "F"].each do |day| %>
      <%= day %> <%= check_box_tag "commute_days[]", day, true, :id => "day_#{day}" %> &nbsp;
  <% end %>
</div>

<div class="mt20">
  Leave home:
  <%= form.select("leave_at", options_for_select(leave_home_at), {include_blank: true}) %>
</div>

<div class="mt20">
  Leave work:
  <%= form.select("return_at", options_for_select(leave_work_at), {include_blank: true}) %>
</div>

<div class="mt20">
  <%= form.text_field :total_seat, placeholder: "Total seat(s)" %>
</div>

<%= form.submit "Submit", class: "btn btn-large btn-success mt30" %>

app/views/rides/_ride.html.erb
<tr id="ride_<%= ride.id %>">
  <td>
    <%= ride.origin %> <br>
    <%= ride.origin_address %>
  </td>
  <td>
    <%= ride.destination %>
  </td>
  <td>
    <%= ride.business_name %> <br>
    <%= ride.destination_address %>
  </td>
  <td>
    <%= ride.status %>:&nbsp;<%= pluralize(ride.total_seat, 'seat') %>
    <br>
    <% if ride.verified_business_email %>
        (Verified Work Email)
    <% end %>
  </td>
  <td>
    <%= ride.commute_days %>
  </td>
  <td>
    Leave : <%= ride.leave_at %> <br>
    Return: <%= ride.return_at %>
  </td>
  <td>
    <% if current_user == ride.user %>
        Your Request!
    <% else %>
        <%= form_for :connection, url: connections_url, method: :post do |form| %>
            <%= form.hidden_field(:ride_id, :value => ride.to_param) %>
            <%= form.submit "Connect", class: "btn btn-large btn-success" %>
        <% end %>
    <% end %>
  </td>
</tr>

app/views/rides/edit.html.erb
<div id="new_ride" class="center">
  <h1>Edit Ride</h1>
</div>


<div class="center">
  <%= form_for :ride, url: ride_url(@ride), method: :put do |form| %>
      <%= render :partial => "form", :object => form %>
  <% end %>
</div>

app/views/rides/index.html.erb
<div id="available_rides" class="center">
  <h1>My Rides</h1>

  <div id="rides">
    <table class="table table-striped table-condensed">
      <thead>
      <tr>
        <td class="bold">Origin</td>
        <td class="bold">Destination</td>
        <td class="bold">Company or Business</td>
        <td class="bold">Type</td>
        <td class="bold">Days</td>
        <td class="bold">Time</td>
        <td class="bold">Actions</td>
      </tr>
      </thead>
      <tbody>
      <% @rides.each do |ride| %>
          <tr id="ride_<%= ride.id %>">
            <td>
              <%= ride.origin %> <br>
              <%= ride.origin_address %>
            </td>
            <td>
              <%= ride.destination %> <br>
            </td>
            <td>
              <%= ride.business_name %>&nbsp;(<%= ride.business_email %>) <br>
              <%= ride.destination_address %>
            </td>
            <td>
              <%= ride.status %>:&nbsp;<%= pluralize(ride.total_seat, 'seat') %>
              <br>
              <% if ride.verified_business_email %>
                  (Verified Work Email)
              <% end %>
            </td>
            <td>
              <%= ride.commute_days %>
            </td>
            <td>
              Leave : <%= ride.leave_at %> <br>
              Return: <%= ride.return_at %>
            </td>
            <td>
              <%= link_to "Edit", edit_ride_path(ride), :class => "btn btn-small btn-success" %>
              <%= link_to "Delete", ride_path(ride), :method => :delete, data: {confirm: "Are you sure?"},
                          :class => "btn btn-small btn-danger" %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rides/new.html.erb
<div id="new_ride" class="center">
  <h1>New Ride</h1>
</div>


<div class="center">
  <%= form_for :ride, url: rides_url, method: :post do |form| %>
      <div>
        <%= form.radio_button("type", "RideRequest") %> Request &nbsp;
        <%= form.radio_button("type", "RideOffer") %> Offer
      </div>

      <div class="mt20">
        <%= form.text_field :origin, placeholder: "Origin" %>
      </div>

      <div class="mt20">
        <%= form.text_field :destination, placeholder: "Destination" %>
      </div>

      <div class="mt20">
        <%= form.text_field :business_name, placeholder: "Company or Business Name" %>
      </div>

      <div class="mt20">
        <%= form.text_field :business_email, placeholder: "Work Email" %>
      </div>

      <div class="mt20">
        <%= form.text_field :total_seat, placeholder: "Total seat(s)" %>
      </div>

      <%= form.submit "Create", class: "btn btn-large btn-success mt30" %>
  <% end %>
</div>

app/views/rides/search.html.erb
<div id="available_rides" class="center">
  <h1>
    Available Rides&nbsp;<%= link_to "Request or Offer a Ride", new_ride_path, :id => "create_new_ride", :class => "btn btn-large btn-primary" %>
  </h1>


  <div id="rides">
    <table class="table table-striped table-condensed">
      <thead>
      <tr>
        <td class="bold">Origin</td>
        <td class="bold">Destination</td>
        <td class="bold">Company or Business</td>
        <td class="bold">Type</td>
        <td class="bold">Days</td>
        <td class="bold">Time (approx)</td>
        <td class="bold">Action</td>
      </tr>
      </thead>
      <tbody>
      <%= render partial: "ride", collection: @rides %>
      </tbody>
    </table>
  </div>


</div>